POST http://localhost:2424/users/signup
Content-Type: application/json

{
  "username": "octaaaaaaaaaaaaaaa",
  "password": "octaPWD",
  "firstName": "Octavio",
  "lastName": "Percivaldi",
  "email": "octavio.percivaldi@mi.unc.edu.ar"
}
